aws:
  regions:
    - 'eu-west-1'
    - 'eu-west-2'
    - 'eu-west-3'
    - 'eu-central-1'
    - 'eu-south-1'
    - 'eu-north-1'
    - 'us-west-1'
    - 'us-west-2'
    - 'us-east-1'
    - 'us-east-2'
    - 'af-south-1'
    - 'ap-east-1'
    - 'ap-southeast-1'
    - 'ap-southeast-2'
    - 'ap-southeast-3'
    - 'ap-south-1'
    - 'ap-northeast-1'
    - 'ap-northeast-2'
    - 'ap-northeast-3'
    - 'ca-central-1'
    - 'sa-east-1'
  iam:
    role_name_suffix: "cicd-automation"
  accounts:
    dev:
      - account_id: '218456729015'
      - account_id: '853107928446'
    tst:
      - account_id: '481375940372'
      - account_id: '624901832567'
    prd:
      - account_id: '964312857039'
      - account_id: '377621048165'
